import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import tw, { styled } from "twin.macro";
import {Box} from '@chakra-ui/react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   
<div>

<section>
  <h1>NEXTJS APP HRERE11212</h1>
</section>


</div>


    </div>
  )
}



const Button = tw.button`
  
  text-white
  font-bold
  py-2
  px-4
  lg:(bg-blue-200 text-black)
sm:(bg-green-200  text-blue-500)
  border
  border-black
  rounded
  background-color[blue]
`;

